server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: chaitanya
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

#    enabled: true
#    timeout: 10
#  cloud:
#    config:
#      import-check:
#        enabled: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

